"""init tables

Revision ID: 5e42d3f1f912
Revises: 59c50b66cd06
Create Date: 2025-10-07 21:42:16.575538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e42d3f1f912'
down_revision: Union[str, Sequence[str], None] = '59c50b66cd06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tradecodes',
    sa.Column('exchange_id', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange_id')
    )
    op.create_table('tradetypes',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('login', sa.String(length=128), nullable=False),
    sa.Column('hash_password', sa.String(length=512), nullable=False),
    sa.Column('last_login_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('refresh_token', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('trades',
    sa.Column('date_open', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_close', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trade_open', sa.Float(), nullable=False),
    sa.Column('trade_close', sa.Float(), nullable=True),
    sa.Column('net_income', sa.Float(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('trade_type_id', sa.Integer(), nullable=False),
    sa.Column('trade_code_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['trade_code_id'], ['tradecodes.id'], ),
    sa.ForeignKeyConstraint(['trade_type_id'], ['tradetypes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    op.drop_table('users')
    op.drop_table('tradetypes')
    op.drop_table('tradecodes')
    # ### end Alembic commands ###
